import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createDrivingState,updateDriving,DRIVE_RADIUS} from '../src/marsDriving.js';

const state=createDrivingState(),w=new Set(['KeyW']);
for(let i=0;i<60;i++)updateDriving(state,w,1/60,[]);
assert.ok(state.z<-2&&state.speed>4,'W drives forward');
for(let i=0;i<60;i++)updateDriving(state,new Set(['KeyW','KeyA']),1/60,[]);
assert.ok(state.heading>.5&&state.x<0,'A steers left while moving');
const obstruction=createDrivingState();for(let i=0;i<240;i++)updateDriving(obstruction,w,1/60,[{x:0,z:-5,radius:1}]);
assert.ok(obstruction.z>-2.6&&obstruction.blocked,'Boulders prevent driving through them');
const edge=createDrivingState();for(let i=0;i<2400;i++)updateDriving(edge,w,1/60,[]);
assert.ok(Math.hypot(edge.x,edge.z)<=DRIVE_RADIUS&&edge.blocked,'The landscape is bounded');
const chrome=process.env.CHROME_PATH||'/opt/google/chrome/chrome';
const browser=await chromium.launch({...(chrome==='playwright'?{}:{executablePath:chrome}),headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const position=()=>page.locator('.rover-canvas').evaluate(e=>({x:+e.dataset.x,z:+e.dataset.z,heading:+e.dataset.heading,speed:+e.dataset.speed}));
const hold=async(key,ms)=>{await page.keyboard.down(key);await page.waitForTimeout(ms);await page.keyboard.up(key);};
await mkdir('.test-artifacts',{recursive:true});
try{
  await page.goto(process.env.BASE_URL||'http://localhost:5173');await page.waitForTimeout(1400);
  await page.getByRole('button',{name:'Explore Mars',exact:true}).click();await page.waitForTimeout(1500);
  await page.getByRole('button',{name:'Find Curiosity',exact:true}).click();assert.equal(await page.locator('.play-rover-button').count(),0);
  await page.getByRole('button',{name:'Close robot information'}).click();
  await page.getByRole('button',{name:'Find Perseverance',exact:true}).click();
  await page.getByRole('button',{name:/Play as Perseverance/}).click();await page.locator('.rover-canvas').waitFor();await page.waitForTimeout(500);
  assert.equal(await page.locator('canvas').count(),1,'The space renderer should be released during driving');
  await page.screenshot({path:'.test-artifacts/rover-demo-desktop.png'});
  await hold('w',1100);assert.ok((await position()).z<-2,'W should move the rover');
  await page.keyboard.down('w');await hold('a',850);await page.keyboard.up('w');
  const left=await position();assert.ok(left.heading>.25&&left.x<-.2,'W+A should turn left');
  await page.keyboard.down('w');await hold('d',850);await page.keyboard.up('w');assert.ok((await position()).heading<left.heading-.2,'D should turn right');
  await page.getByRole('button',{name:'Reset rover',exact:true}).click();await page.waitForTimeout(150);
  assert.ok(Math.hypot((await position()).x,(await position()).z)<.01);
  await page.keyboard.down('s');
  await page.waitForFunction(()=>Number(document.querySelector('.rover-canvas').dataset.z)>1.4,{},{timeout:6000});
  await page.keyboard.up('s');assert.ok((await position()).z>1.4,'S should reverse');
  await page.getByRole('button',{name:'Pause driving',exact:true}).click();await page.waitForTimeout(180);const stopped=await position();await hold('w',500);assert.deepEqual(await position(),stopped,'Pause prevents movement');
  await page.getByRole('button',{name:'Resume driving',exact:true}).click();await hold('w',700);assert.ok((await position()).z<stopped.z,'Resume restores controls');
  await page.keyboard.down('w');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.keyboard.up('w');await page.waitForTimeout(1800);assert.ok((await position()).speed<.03,'Window blur releases driving keys');
  await page.screenshot({path:'.test-artifacts/rover-demo-driving.png'});
  await page.keyboard.press('Escape');await page.locator('.robot-popup').waitFor();assert.equal(await page.locator('#robot-title').textContent(),'Perseverance');assert.equal(await page.locator('.rover-demo').count(),0);
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:/Play as Perseverance/}).click();await page.waitForTimeout(600);
  const forward=await page.getByRole('button',{name:'Drive forward',exact:true}).boundingBox();await page.mouse.move(forward.x+forward.width/2,forward.y+forward.height/2);await page.mouse.down();await page.waitForTimeout(1100);await page.mouse.up();assert.ok((await position()).z<-2,'Touch-style hold buttons drive the rover');
  await page.screenshot({path:'.test-artifacts/rover-demo-mobile.png'});
  await page.getByRole('button',{name:'Back to Mars',exact:true}).click();await page.locator('.robot-popup').waitFor();await page.waitForTimeout(1500);
  assert.equal(await page.locator('canvas').count(),1);assert.equal(await page.locator('#robot-title').textContent(),'Perseverance');assert.deepEqual(errors,[]);
  console.log('Rover acceleration, steering, reverse, obstacles, boundary, pause/resume, key release, touch controls and return to Mars passed.');
}finally{await browser.close();}
