import {interiors} from './interiors';
export const AU = 149597.8707; // Physical units: 1,000 km. Overview rendering compresses orbital spacing.
export const bodies = [
  {id:'sun',name:'Sun',kind:'G-type star',eyebrow:'THE HEART OF IT ALL',tagline:'Our very own star.',description:'The star that holds our neighborhood together. Its light takes just over eight minutes to reach Earth, carrying the energy that makes life possible.',radius:695700,au:0,period:0,day:'27 days',temp:'5,500°C',color:'#e6a45a',angle:0,layers:interiors.sun.layers},
  {id:'mercury',name:'Mercury',kind:'Terrestrial planet',eyebrow:'01 / THE INNER WORLDS',tagline:'Small world. Big extremes.',description:'A cratered, rocky world that races around the Sun in just 88 days. Without a substantial atmosphere, its surface swings between searing heat and bitter cold.',radius:2439.7,au:.387,period:87.97,day:'58.6 days',temp:'167°C',color:'#a69d93',angle:1.1,layers:interiors.mercury.layers},
  {id:'venus',name:'Venus',kind:'Terrestrial planet',eyebrow:'02 / THE INNER WORLDS',tagline:'Beautiful. Unforgiving.',description:'Wrapped in thick clouds, our nearest planetary neighbor hides a volcanic landscape. Its dense atmosphere traps enough heat to make it the hottest planet.',radius:6051.8,au:.723,period:224.7,day:'243 days',temp:'464°C',color:'#d4ba89',angle:2.7,layers:interiors.venus.layers},
  {id:'earth',name:'Earth',kind:'Terrestrial planet',eyebrow:'03 / THE INNER WORLDS',tagline:'There’s no place like home.',description:'An ocean world with a thin, life-giving atmosphere. Our pale blue dot is the only place we know where a universe of life looks back at the stars.',radius:6371,au:1,period:365.25,day:'23.9 hours',temp:'15°C',color:'#77a9bc',angle:4.3,layers:interiors.earth.layers},
  {id:'mars',name:'Mars',kind:'Terrestrial planet',eyebrow:'04 / THE INNER WORLDS',tagline:'The next horizon.',description:'Rust-red deserts, towering volcanoes, and traces of ancient rivers. This quiet world holds clues to a wetter past, and perhaps to life beyond Earth.',radius:3389.5,au:1.524,period:686.98,day:'24.6 hours',temp:'−65°C',color:'#c78364',angle:5.2,layers:interiors.mars.layers},
  {id:'jupiter',name:'Jupiter',kind:'Gas giant',eyebrow:'05 / THE OUTER WORLDS',tagline:'A world of superlatives.',description:'More massive than all the other planets combined. Beneath its swirling cloud bands, storms rage for centuries and hydrogen takes on extraordinary forms.',radius:69911,au:5.203,period:4332.59,day:'9.9 hours',temp:'−110°C',color:'#caa486',angle:1.9,layers:interiors.jupiter.layers},
  {id:'saturn',name:'Saturn',kind:'Gas giant',eyebrow:'06 / THE OUTER WORLDS',tagline:'The ringed wonder.',description:'A world light enough to float in water. Encircled by countless pieces of ice and rock, Saturn is a quiet reminder that the universe has a flair for the extraordinary.',radius:58232,au:9.537,period:10759.22,day:'10.7 hours',temp:'−140°C',color:'#d8c3a0',angle:3.4,layers:interiors.saturn.layers},
  {id:'uranus',name:'Uranus',kind:'Ice giant',eyebrow:'07 / THE OUTER WORLDS',tagline:'A different kind of world.',description:'A serene blue-green planet that rolls around the Sun on its side. Its deep composition remains uncertain: water-rich and rock-rich mixtures both fit current measurements.',radius:25362,au:19.19,period:30688.5,day:'17.2 hours',temp:'−195°C',color:'#91c9cc',angle:5.5,layers:interiors.uranus.layers},
  {id:'neptune',name:'Neptune',kind:'Ice giant',eyebrow:'08 / THE OUTER WORLDS',tagline:'At the edge of the familiar.',description:'Dark, cold, and swept by supersonic winds. The most distant planet in our solar system takes nearly 165 Earth years to complete a single trip around the Sun.',radius:24622,au:30.07,period:60182,day:'16.1 hours',temp:'−200°C',color:'#6e8ecc',angle:.45,layers:interiors.neptune.layers},
  {id:'pluto',name:'Pluto',kind:'Dwarf planet',eyebrow:'09 / BEYOND NEPTUNE',tagline:'A familiar world on the far frontier.',description:'An icy world with nitrogen glaciers, mountains of water ice, and a bright heart-shaped plain. New Horizons revealed this distant member of the solar system up close in 2015.',radius:1188,au:39.48,period:90560,day:'6.4 days',temp:'−230°C',color:'#c7b5a2',angle:2.3,eccentricity:.2488,inclination:17.16,orbitOrientation:4.04,orbitNote:'The orbit is tilted 17.2° and spans about 29.7–49.3 AU from the Sun. Its closest approach briefly lies inside Neptune’s roughly 30.1 AU orbit.',surfaceNote:'New Horizons color mosaic. Unmapped southern regions appear in plain gray. Charon, about half Pluto’s size, orbits every 6.4 Earth days. Its gray surface is illustrative; orbital spacing is compressed and motion accelerated for visibility.',source:'https://science.nasa.gov/dwarf-planets/pluto/facts/',layers:interiors.pluto.layers},
  {id:'belt',name:'Asteroid belt',kind:'Small-body region',eyebrow:'BETWEEN TWO WORLDS',tagline:'Pieces of a planet that never was.',description:'Between Mars and Jupiter, millions of rocky remnants trace wide paths around the Sun. These scattered time capsules preserve the story of our solar system’s beginning.',radius:1,au:2.7,period:1618,day:'Varies',temp:'−73°C',color:'#9caaa4',angle:0,layers:[]},
  {id:'moon',name:'Moon',kind:'Natural satellite',eyebrow:'OUR CLOSEST NEIGHBOR',tagline:'A familiar face in the dark.',description:'Our constant companion. Its cratered surface preserves billions of years of history, while its gentle pull shapes Earth’s tides.',radius:1737.4,au:1,period:27.32,day:'27.3 days',temp:'−20°C',color:'#bababa',angle:4.3,layers:interiors.moon.layers},
];
export const getBody = id => bodies.find(p => p.id === id);
export const destinations = bodies.filter(p=>p.id!=='moon' && p.id!=='belt');
